### ISSUE TITLE
Формирование окружения разработчика

### ISSUE THREAD

**Issue by alehinsasha** [Storm610/FinalTaskRepo#1]
- [x] Внешние отчеты и обработки разбираются на исходники
- [x] Структура каталогов репозитория из bootstrap

**Comment by Storm610** [comment]
Александр, не совсем понимаю что такое bootstrap. Гугл выдаёт "HTML, CSS и Javascript фреймворк для Web-разработки" - это оно?

**Comment by alehinsasha** [comment]
https://github.com/silverbulleters/vanessa-bootstrap

**Comment by alehinsasha** [comment]
В учебных материалах об этом говорится. Если коротко, то это имена каталогов и подкаталогов которые должны быть у вашего проекта. Так сказать, продуманная и согласованная, для единого стандарта модель структуры и и именования.

**Comment by Storm610** [comment]
Разобрался, спасибо!
