### ISSUE TITLE
Разработка по промышленным стандартам

### ISSUE THREAD

**Issue by alehinsasha** [Storm610/FinalTaskRepo#3]
- [x] Одна функциональность = одна фича и сценарии проверяющие работу этой фичи/функциональности
- [x] Использование фикстур
- [x] Повторное использование шагов (собственная библиотека шагов)
- [x] Фичи из воздуха
- [x] Детализация фичи

**Comment by alehinsasha** [comment]
**В дополнение к проверке навыка "Повторное использование шагов (собственная библиотека шагов)"**

Для подтверждения этого навыка у вас должно быть:
1. Две фичи проверяющие поступление и продажу товара.
2. В каталоге features каталог в котором вы будете хранить ваши библиотечные фичи.
3. В этом каталоге библиотечных шагов должна быть одна фича с одним универсальным (параметризованным) шагом который будет удалять документы.
4. В фичах поступления и продажи нужно использовать этот библиотечный шаг.

**Comment by Storm610** [comment]
Александр, такой вопрос:
Основанием для начала разработки служит фича, но что бы получить фичу из воздуха, соответствующий функционал уже должен быть разработан.
И согласовать фичу с заказчиком я могу только после того как разработан функционал?

**Comment by alehinsasha** [comment]
"Фичи из воздуха" - это функциональность vanessa-behavior, которая использует "автоматизированного тестирования 1С".  "Фича" - это файл, в которым вы с клиентом договариваетесь о функционале и о том как будете его проверять. Далее можно корректировать фичу, если у вас развернуто окружение разработчика, и все изменения фичи будут обоснованы в описании коммитов.

P.S. вы действительно думаете что мы на практике сидим у заказчика годами, такие зацикленные и не знаем что делать, фичу писать или функциональность реализовывать?

**Comment by Storm610** [comment]
Конечно же я так не думаю.

**Comment by Storm610** [comment]
Первичная фича, с которой начинается разработка, пишется в BDDEditor, а с помощью "фич из воздуха" она дополняется, детализируется и т.д.  по мере реализации функционала. Правильно понимаю?

**Comment by alehinsasha** [comment]
Правильно.
