### ISSUE TITLE
Демонстрация работ заказчику

### ISSUE THREAD

**Issue by alehinsasha** [Storm610/FinalTaskRepo#5]
**Что нужно сделать**
1. Выгрузить конфигурацию в файлы (конфигуратор → конфигурация → выгрузить конфигурацию в файлы → <ИмяРепозиторияФинальногоЗадания>\src\cf);
2. Закоммитить и отправить во внешний репозиторий.

**Особенности**
- Приступать к выполнению этой задачи нужно после того как закроете все созданные мной issue.
- В публичный внешний репозиторий, нельзя помещать код из типовых конфигураций 1С!

**Comment by alehinsasha** [comment]
Жду исходники конфигурации в \src\cf

**Comment by Storm610** [comment]
файлы выгружены

**Comment by alehinsasha** [comment]
готово
