### ISSUE TITLE
Сообщить данные для получения сертификата финалиста

### ISSUE THREAD

**Issue by alehinsasha** [Storm610/FinalTaskRepo#6]
В комментарии к этому issue напишите ваши:
- Имя Фамилию (в дательном падеже)
- Адрес электронной почты, на которую выслать сертификат

**Comment by Storm610** [comment]
Роману Давыдову
whitefist@mail.ru

**Comment by alehinsasha** [comment]
Поздравительное письмо отправлено на указанный адрес! Прошу подтвердить получение.

**Comment by Storm610** [comment]
получил, спасибо!

**Comment by alehinsasha** [comment]
Вам, удачи и успеха!
